name: Update Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "23 3 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main", "test"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Classic Metrics
        uses: lowlighter/metrics@v3.34
        with:
          filename: metrics.classic.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, repositories
          plugin_lines: yes
      - name: Starred repositories
        uses: lowlighter/metrics@v3.34
        with:
          filename: metrics.plugin.repositories.starred.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_repositories: yes
          plugin_repositories_starred: 10
      - name: Full history calendar
        uses: lowlighter/metrics@v3.34
        with:
          filename: metrics.plugin.calendar.full.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_calendar: yes
          plugin_calendar_limit: 0
      - name: Languages
        uses: lowlighter/metrics@v3.34
        with:
          filename: metrics.plugin.languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_indepth: yes
